title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages...
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
url: "https://ww2.xdoc.app"  # Your custom domain
baseurl: ""  # Leave this empty since your site is at the root
